module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Semantic theme colors (auto-switch via CSS vars)
        "th-bg": "var(--color-bg)",
        "th-surface": "var(--color-surface)",
        "th-card": "var(--color-card)",
        "th-card-hover": "var(--color-card-hover)",
        "th-card-active": "var(--color-card-active)",
        "th-text": "var(--color-text)",
        "th-text-secondary": "var(--color-text-secondary)",
        "th-text-muted": "var(--color-text-muted)",
        "th-border": "var(--color-border)",
        "th-border-muted": "var(--color-border-muted)",
        "th-primary": "var(--color-primary)",
        "th-primary-hover": "var(--color-primary-hover)",
        "th-primary-text": "var(--color-primary-text)",
        "th-primary-container": "var(--color-primary-container)",
        "th-primary-container-text": "var(--color-primary-container-text)",
        "th-input-bg": "var(--color-input-bg)",
        "th-input-text": "var(--color-input-text)",
        "th-input-border": "var(--color-input-border)",
        "th-badge-bg": "var(--color-badge-bg)",
        "th-badge-text": "var(--color-badge-text)",
        "th-info-bg": "var(--color-info-bg)",
        "th-info-text": "var(--color-info-text)",
        "th-info-border": "var(--color-info-border)",
        "th-cancel-bg": "var(--color-cancel-bg)",
        "th-cancel-text": "var(--color-cancel-text)",
        "th-nav-bg": "var(--color-nav-bg)",
        "th-nav-border": "var(--color-nav-border)",
        "th-error": "var(--color-error)",
        "th-error-container": "var(--color-error-container)",
        // Keep existing Material tokens for Login/Stitch components
        "outline": "#8f909a",
        "background": "var(--color-bg)",
        "on-secondary-container": "#b5b9bf",
        "surface-container-lowest": "var(--color-bg)",
        "surface-container-low": "var(--color-surface)",
        "on-tertiary-container": "#7a452d",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed-variant": "#6c3922",
        "on-surface": "var(--color-text)",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#334576",
        "surface-bright": "#39393b",
        "surface": "var(--color-surface)",
        "secondary-container": "#454a4f",
        "surface-dim": "var(--color-bg)",
        "on-primary-fixed": "#021848",
        "on-primary": "#1c2e5e",
        "on-background": "var(--color-text)",
        "severity-high": "#ef4444",
        "surface-container-high": "var(--color-card-hover)",
        "inverse-surface": "#e5e1e4",
        "on-secondary-fixed": "#171c20",
        "border-muted": "var(--color-border-muted)",
        "on-primary-container": "#405183",
        "primary": "var(--color-primary)",
        "tertiary-container": "#ffb697",
        "surface-variant": "var(--color-card-active)",
        "on-tertiary": "#51230e",
        "surface-container-highest": "var(--color-input-bg)",
        "secondary": "#c3c7cd",
        "secondary-fixed-dim": "#c3c7cd",
        "surface-tint": "#b4c5ff",
        "surface-container": "var(--color-card)",
        "tertiary-fixed": "#ffdbcd",
        "outline-variant": "var(--color-border)",
        "on-surface-variant": "var(--color-text-secondary)",
        "primary-container": "var(--color-primary-container)",
        "error": "var(--color-error)",
        "inverse-primary": "#4c5c90",
        "severity-low": "#f59e0b",
        "text-primary": "var(--color-text)",
        "on-tertiary-fixed": "#360f00",
        "on-error-container": "#ffdad6",
        "error-container": "var(--color-error-container)",
        "tertiary-fixed-dim": "#ffb597",
        "text-secondary": "var(--color-text-secondary)",
        "secondary-fixed": "#dfe3e9",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#303032",
        "tertiary": "#ffdbce",
        "on-secondary-fixed-variant": "#43474c",
        "on-secondary": "#2c3136"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit": "4px",
        "container-max": "1000px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Outfit"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Outfit"],
        "display-lg": ["Outfit"]
      }
    },
  },
  plugins: [],
}
